// Legal disclaimer page — long-form version of the footer one-liner.
// Static SSR. Wording must be reviewed by an Australian solicitor per
// docs/legal/disclaimer-text.md before public launch (hard gate).

import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Legal Disclaimer — nosurcharging.com.au',
  description:
    'Legal disclaimer for nosurcharging.com.au — nature of service, AFSL position, accuracy of estimates, independence, and limitation of liability.',
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-paper">
      <article
        className="mx-auto max-w-results px-5 pt-16 pb-20"
      >
        <Link
          href="/"
          className="block text-accent hover:underline"
          style={{
            fontSize: '13px',
            textUnderlineOffset: '2px',
            marginBottom: '40px',
          }}
        >
          ← Back
        </Link>

        <h1
          className="font-serif text-ink"
          style={{
            fontSize: '32px',
            fontWeight: 500,
            letterSpacing: '-0.5px',
            lineHeight: 1.15,
            marginBottom: '6px',
          }}
        >
          Legal Disclaimer
        </h1>
        <p
          className="text-ink-faint"
          style={{ fontSize: '13px', marginBottom: '48px' }}
        >
          Last updated April 2026 · nosurcharging.com.au
        </p>

        <Section title="Nature of this service">
          <p>
            This website provides general information and educational content
            about the Reserve Bank of Australia&apos;s 2026 surcharge reform.
            Nothing on this website constitutes financial product advice,
            financial services advice, legal advice, accounting advice, or any
            other professional advice of any kind. The assessments,
            calculations, P&amp;L estimates, action plans, and negotiation
            scripts generated by this tool are illustrative estimates only and
            are not a substitute for advice from a qualified financial adviser,
            accountant, payments specialist, or legal practitioner.
          </p>
        </Section>

        <Section title="Not an AFSL holder">
          <p>
            nosurcharging.com.au does not hold an Australian Financial Services
            Licence (AFSL) and is not authorised to provide financial product
            advice under the Corporations Act 2001 (Cth). This service does not
            recommend, endorse, or advise you to enter into, exit from, or hold
            any financial product or arrangement. Before making any changes to
            your payment processing arrangements, pricing structure, or
            provider contracts, you should seek independent advice from a
            licensed professional.
          </p>
        </Section>

        <Section title="Accuracy of estimates">
          <p>
            All dollar figures, percentage savings, P&amp;L impacts, and cost
            estimates produced by this tool are estimates based on publicly
            available data including the Reserve Bank of Australia&apos;s
            Conclusions Paper (March 2026), published interchange rate
            schedules, and average market rates. Your actual financial outcome
            will depend on factors specific to your business including your
            actual card mix, transaction volumes, payment provider contract
            terms, and decisions made by your payment service provider after 1
            October 2026. Figures may differ materially from your actual
            result. nosurcharging.com.au makes no representation or warranty,
            express or implied, as to the accuracy, completeness, reliability,
            or suitability of any estimate or calculation produced by this
            tool.
          </p>
        </Section>

        <Section title="Independence and no commercial relationships">
          <p>
            nosurcharging.com.au is independent and has no commercial
            relationship, referral arrangement, commission agreement, or
            financial interest with any payment service provider, acquirer,
            payment facilitator, or financial institution named or referenced
            on this website. PSP names, contact details, and rate information
            are included for informational purposes only. Their inclusion does
            not constitute a recommendation or endorsement.
          </p>
        </Section>

        <Section title="Reform details subject to change">
          <p>
            The RBA surcharge reform is subject to finalisation of regulatory
            instruments, final interchange schedule determinations, and
            implementation decisions by individual payment networks and
            acquirers. Information on this website reflects publicly available
            information as at the date of publication and may not reflect
            subsequent developments. nosurcharging.com.au is under no
            obligation to update information following publication.
          </p>
        </Section>

        <Section title="Limitation of liability">
          <p>
            To the maximum extent permitted by applicable law,
            nosurcharging.com.au, its operators, contributors, and affiliates
            exclude all liability for any loss or damage of any kind (including
            direct, indirect, consequential, or economic loss) arising from
            your use of or reliance on this website, any estimate or
            calculation produced by this tool, or any action or inaction taken
            in response to information on this website. Where liability cannot
            be excluded by law, our liability is limited to the maximum extent
            permitted under the Australian Consumer Law.
          </p>
        </Section>

        <Section title="Governing law">
          <p>
            This website is operated from Australia. These terms and any
            dispute arising from your use of this website are governed by the
            laws of New South Wales, Australia.
          </p>
        </Section>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2
        className="text-ink"
        style={{
          fontSize: '15px',
          fontWeight: 700,
          marginTop: '40px',
          marginBottom: '12px',
        }}
      >
        {title}
      </h2>
      <div
        style={{
          fontSize: '13px',
          color: '#6B5E4A',
          lineHeight: 1.65,
        }}
      >
        {children}
      </div>
    </section>
  );
}
