'use server';

// captureEmail — server-side helper invoked by submitAssessment after the
// assessments row has been INSERTed. Sends the results-report email via
// Resend and stamps email_report_sent / email_report_sent_at on success.
//
// The merchant's email + marketing_consent are stored on the assessments
// row itself by submitAssessment — this action never writes them. It only
// performs the transactional Resend send.
//
// Behavioural contract:
//   - Never throws. Returns { success } regardless of Resend outcome.
//   - DB UPDATE is best-effort (mirrors Resend success).
//   - RESEND_API_KEY missing → action returns success with a console
//     warning. The DB row is untouched (email_report_sent stays false).

import { Resend } from 'resend';
import { supabaseAdmin } from '@/lib/supabase/server';
import { sanitiseForHTML } from '@/lib/security';
import { CATEGORY_VERDICTS } from '@nosurcharging/calculations/categories';
import type { AssessmentOutputs, ActionItem } from '@nosurcharging/calculations/types';

export interface CaptureEmailPayload {
  assessmentId: string;
  email: string;
}

export interface CaptureEmailResult {
  success: boolean;
  error?: 'invalid_assessment_id' | 'unexpected_error';
}

// Lazy-init pattern (same as submitFeedback.ts and the calendly webhook).
// Resend constructor throws when the key is missing at construction time —
// defer to runtime so CI builds without RESEND_API_KEY succeed.
function getResend(): Resend | null {
  const key = process.env.RESEND_API_KEY;
  if (!key) return null;
  return new Resend(key);
}

function formatSignedDollar(v: number): string {
  if (v === 0) return '$0';
  const abs = Math.abs(Math.round(v)).toLocaleString('en-AU');
  return (v > 0 ? '+' : '−') + '$' + abs;
}

function buildResultsEmailBody(args: {
  category: 1 | 2 | 3 | 4 | 5;
  verdict: string;
  plSwing: string;
  reportUrl: string;
  firstAction: string;
}): string {
  return `Your assessment is complete.

You're in Situation ${args.category} — ${args.verdict}

Your estimated annual impact from 1 October 2026:
${args.plSwing}

View your full report:
${args.reportUrl}

—

One step to take today:
${args.firstAction}

—

This report was generated by nosurcharging.com.au, an independent payments
intelligence platform. Not financial advice. Figures are estimates based on
the information you provided.

Unsubscribe from results emails: reply STOP to this email.

nosurcharging.com.au is not affiliated with any payment service provider,
bank, or acquirer.`;
}

export async function captureEmail(
  payload: CaptureEmailPayload,
): Promise<CaptureEmailResult> {
  try {
    if (!payload.assessmentId || !/^[0-9a-f-]{36}$/.test(payload.assessmentId)) {
      return { success: false, error: 'invalid_assessment_id' };
    }

    const email = (payload.email ?? '').toLowerCase().trim();
    if (!email) {
      // Defensive — submitAssessment only invokes captureEmail when an email
      // was provided, but we double-check rather than send to "".
      return { success: true };
    }

    const resend = getResend();
    if (!resend) {
      console.warn('[captureEmail] RESEND_API_KEY not set — skipping report send');
      return { success: true };
    }

    // Read the outputs we just INSERTed so the email matches what the
    // merchant will see at /results.
    const { data: row, error: selectError } = await supabaseAdmin
      .from('assessments')
      .select('outputs')
      .eq('id', payload.assessmentId)
      .single();

    if (selectError || !row) {
      console.error('[captureEmail] outputs fetch failed:', selectError?.message);
      return { success: true };
    }

    const outputs = row.outputs as AssessmentOutputs & { actions?: ActionItem[] };
    const verdict = CATEGORY_VERDICTS[outputs.category];
    const plSwing = formatSignedDollar(outputs.plSwing);
    const firstAction =
      outputs.actions?.[0]?.text ?? 'Open your full report and review the action plan.';
    const reportUrl = `https://nosurcharging.com.au/results?id=${payload.assessmentId}`;

    const body = buildResultsEmailBody({
      category: outputs.category,
      verdict,
      plSwing,
      reportUrl,
      firstAction,
    });

    try {
      await resend.emails.send({
        // Use || so an empty-string env var also falls back to the default.
        from: process.env.RESEND_FROM || 'results@nosurcharging.com.au',
        to: sanitiseForHTML(email),
        subject: 'Your payments reform assessment — nosurcharging.com.au',
        text: body,
      });

      // Resend ack'd — stamp email_report_sent
      await supabaseAdmin
        .from('assessments')
        .update({
          email_report_sent: true,
          email_report_sent_at: new Date().toISOString(),
        })
        .eq('id', payload.assessmentId);
    } catch (err) {
      console.error('[captureEmail] Resend send failed:', (err as Error).message);
      // DB row is untouched — email_report_sent stays false. Retry is out of
      // scope for v1. Sentry will surface the failure to ops.
    }

    return { success: true };
  } catch (err) {
    console.error('[captureEmail] unexpected error:', (err as Error).message);
    return { success: false, error: 'unexpected_error' };
  }
}
